spring.application.name=activity01

spring.datasource.url=jdbc:mysql://localhost:3306/l23y19w18
spring.datasource.username=L23Y19W18
spring.datasource.password=749794Veinz!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
